{"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/182", "repository_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT", "labels_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/182/labels{/name}", "comments_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/182/comments", "events_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/182/events", "html_url": "https://github.com/Significant-Gravitas/Auto-GPT/issues/182", "id": 1654082309, "node_id": "I_kwDOJKSTjM5il0sF", "number": 182, "title": "How to use a proxy and where to configure it?\uff08v2rayN)", "user": {"login": "xillkoi", "id": 82936603, "node_id": "MDQ6VXNlcjgyOTM2NjAz", "avatar_url": "https://avatars.githubusercontent.com/u/82936603?v=4", "gravatar_id": "", "url": "https://api.github.com/users/xillkoi", "html_url": "https://github.com/xillkoi", "followers_url": "https://api.github.com/users/xillkoi/followers", "following_url": "https://api.github.com/users/xillkoi/following{/other_user}", "gists_url": "https://api.github.com/users/xillkoi/gists{/gist_id}", "starred_url": "https://api.github.com/users/xillkoi/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/xillkoi/subscriptions", "organizations_url": "https://api.github.com/users/xillkoi/orgs", "repos_url": "https://api.github.com/users/xillkoi/repos", "events_url": "https://api.github.com/users/xillkoi/events{/privacy}", "received_events_url": "https://api.github.com/users/xillkoi/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 5347563882, "node_id": "LA_kwDOJKSTjM8AAAABPr1Zag", "url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/labels/setup", "name": "setup", "color": "E1BC6F", "default": false, "description": "Issues with getting Auto-GPT setup on local machines"}, {"id": 5401552627, "node_id": "LA_kwDOJKSTjM8AAAABQfUm8w", "url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/labels/needs%20investigation", "name": "needs investigation", "color": "C3708F", "default": false, "description": ""}, {"id": 5409115183, "node_id": "LA_kwDOJKSTjM8AAAABQmiMLw", "url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/labels/API%20access", "name": "API access", "color": "C5A39D", "default": false, "description": "Trouble with connecting to the API"}], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 9, "created_at": "2023-04-04T15:09:31Z", "updated_at": "2023-04-25T22:28:45Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "raise error.APIConnectionError(\r\nopenai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))", "reactions": {"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/182/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/182/timeline", "performed_via_github_app": null, "state_reason": "reopened"}