{"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3042", "repository_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT", "labels_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3042/labels{/name}", "comments_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3042/comments", "events_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3042/events", "html_url": "https://github.com/Significant-Gravitas/Auto-GPT/issues/3042", "id": 1680100841, "node_id": "I_kwDOJKSTjM5kJE3p", "number": 3042, "title": "Command for pre-seeding missing", "user": {"login": "psvensson", "id": 39554, "node_id": "MDQ6VXNlcjM5NTU0", "avatar_url": "https://avatars.githubusercontent.com/u/39554?v=4", "gravatar_id": "", "url": "https://api.github.com/users/psvensson", "html_url": "https://github.com/psvensson", "followers_url": "https://api.github.com/users/psvensson/followers", "following_url": "https://api.github.com/users/psvensson/following{/other_user}", "gists_url": "https://api.github.com/users/psvensson/gists{/gist_id}", "starred_url": "https://api.github.com/users/psvensson/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/psvensson/subscriptions", "organizations_url": "https://api.github.com/users/psvensson/orgs", "repos_url": "https://api.github.com/users/psvensson/repos", "events_url": "https://api.github.com/users/psvensson/events{/privacy}", "received_events_url": "https://api.github.com/users/psvensson/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 5347563882, "node_id": "LA_kwDOJKSTjM8AAAABPr1Zag", "url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/labels/setup", "name": "setup", "color": "E1BC6F", "default": false, "description": "Issues with getting Auto-GPT setup on local machines"}, {"id": 5405679248, "node_id": "LA_kwDOJKSTjM8AAAABQjQekA", "url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/labels/docker", "name": "docker", "color": "5152EA", "default": false, "description": ""}], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2023-04-23T17:20:24Z", "updated_at": "2023-04-24T04:56:36Z", "closed_at": null, "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "### \u26a0\ufe0f Search for existing issues first \u26a0\ufe0f\n\n- [X] I have searched the existing issues, and there is no existing issue for my problem\n\n### Which Operating System are you using?\n\nDocker\n\n### Which version of Auto-GPT are you using?\n\nMaster (branch)\n\n### GPT-3 or GPT-4?\n\nGPT-3.5\n\n### Steps to reproduce \ud83d\udd79\n\nThe README (https://github.com/Significant-Gravitas/Auto-GPT/blob/master/docs/configuration/memory.md) saty that pre-seeding could be done by running the command python data_ingestion.py. However this does not work in docker.\r\n\r\nThe file data_ingestion.py is not there.\r\n\r\nOn Dicord Bill Scgumacher thought that the functionality now had moved into the autogpt module, but it was not possible to start it from there either (runnin exec inside a docker container)\n\n### Current behavior \ud83d\ude2f\n\npython -m autogpt.data_ingestion\r\n/usr/local/bin/python: No module named autogpt.data_ingestion\n\n### Expected behavior \ud83e\udd14\n\nBeing able to pre-seed memory, and the README to reflect how the system works plz\n\n### Your prompt \ud83d\udcdd\n\n```yaml\r\n# no prompt\r\n```\r\n\n\n### Your Logs \ud83d\udcd2\n\n```log\r\npython -m autogpt:data_ingestion\r\n/usr/local/bin/python: No module named autogpt:data_ingestion\r\n\r\n```\r\n", "reactions": {"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3042/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3042/timeline", "performed_via_github_app": null, "state_reason": null}