{"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2015", "repository_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT", "labels_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2015/labels{/name}", "comments_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2015/comments", "events_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2015/events", "html_url": "https://github.com/Significant-Gravitas/Auto-GPT/issues/2015", "id": 1670156657, "node_id": "I_kwDOJKSTjM5jjJFx", "number": 2015, "title": "'The JSON object is invalid' Every task results in a 'do_nothing' command", "user": {"login": "fewmatty", "id": 130803548, "node_id": "U_kgDOB8vnXA", "avatar_url": "https://avatars.githubusercontent.com/u/130803548?v=4", "gravatar_id": "", "url": "https://api.github.com/users/fewmatty", "html_url": "https://github.com/fewmatty", "followers_url": "https://api.github.com/users/fewmatty/followers", "following_url": "https://api.github.com/users/fewmatty/following{/other_user}", "gists_url": "https://api.github.com/users/fewmatty/gists{/gist_id}", "starred_url": "https://api.github.com/users/fewmatty/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/fewmatty/subscriptions", "organizations_url": "https://api.github.com/users/fewmatty/orgs", "repos_url": "https://api.github.com/users/fewmatty/repos", "events_url": "https://api.github.com/users/fewmatty/events{/privacy}", "received_events_url": "https://api.github.com/users/fewmatty/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 5347563882, "node_id": "LA_kwDOJKSTjM8AAAABPr1Zag", "url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/labels/setup", "name": "setup", "color": "E1BC6F", "default": false, "description": "Issues with getting Auto-GPT setup on local machines"}], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 13, "created_at": "2023-04-16T21:46:38Z", "updated_at": "2023-04-23T14:54:45Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "### \u26a0\ufe0f Search for existing issues first \u26a0\ufe0f\n\n- [X] I have searched the existing issues, and there is no existing issue for my problem\n\n### GPT-3 or GPT-4\n\n- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)\n\n### Steps to reproduce \ud83d\udd79\n\nI've added the file_operations.py file that seemed to work for others on this reddit thread: https://www.reddit.com/r/AutoGPT/comments/12j70go/saving_files/\r\n\r\nI am trying to have autogpt use information found online related to my original prompt to create and add data to an excel file. \r\n\r\nIt is doing a fine job finding the relevant information, but cannot create or save a file.\r\n\r\n<img width=\"884\" alt=\"Screenshot 2023-04-16 at 5 44 05 PM\" src=\"https://user-images.githubusercontent.com/130803548/232344143-ca16de95-9f40-41b4-a297-edbb0a4e0f9e.png\">\r\n\n\n### Current behavior \ud83d\ude2f\n\nevery next action gives a 'do_nothing' so it is doing nothing.\n\n### Expected behavior \ud83e\udd14\n\nI am trying to get autogpt to create an excel file, use information from a folder on my desktop and the internet to complete my objective. \r\n\r\nIn this case, it is to create a business proposal for a liquor store (job I did on upwork a while back - trying to replicate with autogpt)\r\n\r\nIF ANYONE CAN HELP I WOULD APPRECIATE A TON\n\n### Your prompt \ud83d\udcdd\n\n```yaml\r\n# Paste your prompt here\r\n```\r\n", "reactions": {"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2015/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2015/timeline", "performed_via_github_app": null, "state_reason": null}