{"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1106", "repository_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT", "labels_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1106/labels{/name}", "comments_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1106/comments", "events_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1106/events", "html_url": "https://github.com/Significant-Gravitas/Auto-GPT/issues/1106", "id": 1666400979, "node_id": "I_kwDOJKSTjM5jU0LT", "number": 1106, "title": "gitignore ai_settings.yaml and add template to repo", "user": {"login": "p-i-", "id": 693495, "node_id": "MDQ6VXNlcjY5MzQ5NQ==", "avatar_url": "https://avatars.githubusercontent.com/u/693495?v=4", "gravatar_id": "", "url": "https://api.github.com/users/p-i-", "html_url": "https://github.com/p-i-", "followers_url": "https://api.github.com/users/p-i-/followers", "following_url": "https://api.github.com/users/p-i-/following{/other_user}", "gists_url": "https://api.github.com/users/p-i-/gists{/gist_id}", "starred_url": "https://api.github.com/users/p-i-/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/p-i-/subscriptions", "organizations_url": "https://api.github.com/users/p-i-/orgs", "repos_url": "https://api.github.com/users/p-i-/repos", "events_url": "https://api.github.com/users/p-i-/events{/privacy}", "received_events_url": "https://api.github.com/users/p-i-/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2023-04-13T13:14:33Z", "updated_at": "2023-04-18T05:36:24Z", "closed_at": null, "author_association": "COLLABORATOR", "active_lock_reason": null, "body": "### Duplicates\n\n- [X] I have searched the existing issues\n\n### Steps to reproduce \ud83d\udd79\n\n`git pull` may delete your `ai_settings.yaml`\r\n\r\nIt may fail due to a conflict with this file.\r\n\r\nGrateful if someone can clean this up.\n\n### Current behavior \ud83d\ude2f\n\nIt can fail.\n\n### Expected behavior \ud83e\udd14\n\nIt should succeed.\n\n### Your prompt \ud83d\udcdd\n\nPrompt N/A here.\r\n\r\nIssue is this:\r\n\r\nhttps://github.com/Torantulino/Auto-GPT/pull/742\r\n^ This PR removed ai_settings.yaml as the file gets autogenerated on the first run.\r\n\r\nCurrent `master` does NOT have this file.\r\nCurrent `stable` DOES have this file. Not sure how that happened.\r\n\r\nOne developer gets one problem (`git pull` failed due to conflict over `ai_settings.yaml`)\r\nAnother developer reports a different problem (`ai_settings.yaml` removed)\r\n\r\nThis needs to be tidied up.\r\n\r\nMy suggestion:\r\n- A `ai_settings.yaml.example` file in the repo (but no `ai_settings.yaml`)\r\n- When `main.py` executes, it looks for `ai_settings.yaml`\r\n  - If found, it uses these values\r\n  - If not, it loads the values from ai_settings.yaml.example and prompts the user whether they wish to modify these default values\r\n  - The default `ai_role` looks suspiciously like a PaperClip Optimizer:\r\n    ```\r\n      ai_role: an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.\r\n    ```\r\n   \r\n    How about: \r\n    ```\r\n      ai_role: an AI designed to autonomously develop and operate a profitable and ethical business.\r\n    ```\r\n\r\nGrateful if someone takes a look. Welcome to ping me on the Discord pi#8377.", "reactions": {"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1106/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1106/timeline", "performed_via_github_app": null, "state_reason": null}