{"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2330", "repository_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT", "labels_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2330/labels{/name}", "comments_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2330/comments", "events_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2330/events", "html_url": "https://github.com/Significant-Gravitas/Auto-GPT/issues/2330", "id": 1672509157, "node_id": "I_kwDOJKSTjM5jsHbl", "number": 2330, "title": "Google search fails with 400 Bad request: Request contains an invalid argument", "user": {"login": "Monjai95xd", "id": 130657205, "node_id": "U_kgDOB8mrtQ", "avatar_url": "https://avatars.githubusercontent.com/u/130657205?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Monjai95xd", "html_url": "https://github.com/Monjai95xd", "followers_url": "https://api.github.com/users/Monjai95xd/followers", "following_url": "https://api.github.com/users/Monjai95xd/following{/other_user}", "gists_url": "https://api.github.com/users/Monjai95xd/gists{/gist_id}", "starred_url": "https://api.github.com/users/Monjai95xd/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Monjai95xd/subscriptions", "organizations_url": "https://api.github.com/users/Monjai95xd/orgs", "repos_url": "https://api.github.com/users/Monjai95xd/repos", "events_url": "https://api.github.com/users/Monjai95xd/events{/privacy}", "received_events_url": "https://api.github.com/users/Monjai95xd/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2023-04-18T07:19:57Z", "updated_at": "2023-04-27T00:35:01Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "### \u26a0\ufe0f Search for existing issues first \u26a0\ufe0f\n\n- [X] I have searched the existing issues, and there is no existing issue for my problem\n\n### GPT-3 or GPT-4\n\n- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)\n\n### Steps to reproduce \ud83d\udd79\n\nEach time when Auto-GPT try to google something, it return the same message like this.\r\nHow to solve it? T^T\r\n\r\nSYSTEM:  Command google returned: Error: <HttpError 400 when requesting https://customsearch.googleapis.com/customsearch/v1?q=top+5+social+media+platforms+2023%3B+5+emerging+social+media+platforms+2023&cx=autogpt-383613&num=8&key=AIzaSyDOf6f0U-erJubJjHFA1-KmmT97T720Z8Y&alt=json returned \"Request contains an invalid argument.\". Details: \"[{'message': 'Request contains an invalid argument.', 'domain': 'global', 'reason': 'badRequest'}]\">\n\n### Current behavior \ud83d\ude2f\n\n_No response_\n\n### Expected behavior \ud83e\udd14\n\n_No response_\n\n### Your prompt \ud83d\udcdd\n\n```yaml\r\n# Paste your prompt here\r\n```\r\n", "reactions": {"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2330/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/2330/timeline", "performed_via_github_app": null, "state_reason": null}